import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ width: "100%", height: "100%", margin: 0, padding: 0, overflow: "hidden" }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ width: "100%", height: "100dvh", margin: 0, padding: 0, overflow: "hidden", background: "#d8e6f6" }}
      >
        {children}
      </body>
    </html>
  );
}
