import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Create Next App",
    short_name: "NextApp",
    description: "Generated by create next app",
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#ffffff",
    icons: [
      { src: "public/images/title.png", sizes: "192x192", type: "image/png" },
      { src: "public/images/title.png", sizes: "512x512", type: "image/png" },
    ],
  };
}
